defmodule Hello.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversation_members, primary_key: false) do
      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_members_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :member_id,
          references(:users,
            column: :id,
            name: "conversation_members_member_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create index(:conversation_members, [:conversation_id])
  end

  def down do
    drop_if_exists index(:conversation_members, [:conversation_id])

    drop constraint(:conversation_members, "conversation_members_conversation_id_fkey")

    drop constraint(:conversation_members, "conversation_members_member_id_fkey")

    drop table(:conversation_members)
  end
end
