defmodule Hello.Repo.Migrations.CreateEmbeddingSections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :chunk, :text
      add :metadata, :map
      add :embedding, :vector, size: 384

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:sections, ["embedding vector_cosine_ops"],
             name: "embeddings_index",
             using: "hnsw"
           )
  end

  def down do
    drop_if_exists index(:sections, ["embedding vector_cosine_ops"], name: "embeddings_index")

    drop table(:sections)
  end
end
