defmodule Hello.Repo.Migrations.AddPasswordAuthenticationAndAddPasswordAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :hashed_password, :text
      add :confirmed_at, :utc_datetime_usec
    end

    create table(:user_conversations, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "user_conversations_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :conversation_id, :uuid, null: false, primary_key: true
    end

    alter table(:sections) do
      add :content_hash, :text, null: false
    end

    create index(:sections, ["content_hash"], name: "content_hash_index")

    create unique_index(:sections, [:content_hash], name: "sections_unique_content_hash_index")

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false
      add :sender_type, :text, null: false

      add :sender_id,
          references(:users,
            column: :id,
            name: "messages_sender_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id, :uuid, null: false
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_conversations) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "user_conversations_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:user_conversations, [:user_id])

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversations) do
      add :title, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:conversations) do
      remove :updated_at
      remove :inserted_at
      remove :title
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id, :uuid
    end

    drop_if_exists index(:user_conversations, [:user_id])

    drop constraint(:user_conversations, "user_conversations_conversation_id_fkey")

    alter table(:user_conversations) do
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop constraint(:messages, "messages_sender_id_fkey")

    drop table(:messages)

    drop_if_exists unique_index(:sections, [:content_hash],
                     name: "sections_unique_content_hash_index"
                   )

    drop_if_exists index(:sections, ["content_hash"], name: "content_hash_index")

    alter table(:sections) do
      remove :content_hash
    end

    drop constraint(:user_conversations, "user_conversations_user_id_fkey")

    drop table(:user_conversations)

    alter table(:users) do
      remove :confirmed_at
      remove :hashed_password
    end
  end
end
