defmodule Hello.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_conversations, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "user_conversations_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "user_conversations_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false
    end

    create index(:user_conversations, [:user_id])

    alter table(:conversations) do
      remove :user_id
    end
  end

  def down do
    alter table(:conversations) do
      add :user_id,
          references(:users,
            column: :id,
            name: "conversations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists index(:user_conversations, [:user_id])

    drop constraint(:user_conversations, "user_conversations_user_id_fkey")

    drop constraint(:user_conversations, "user_conversations_conversation_id_fkey")

    drop table(:user_conversations)
  end
end
