defmodule Hello.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:sections, [:content_hash], name: "sections_unique_content_hash_index")
  end

  def down do
    drop_if_exists unique_index(:sections, [:content_hash],
                     name: "sections_unique_content_hash_index"
                   )
  end
end
