defmodule Hello.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:sections, ["content_hash"], name: "unique_content_hash_index")

    create index(:sections, ["content_hash"], name: "content_hash_index")
  end

  def down do
    drop_if_exists index(:sections, ["content_hash"], name: "content_hash_index")

    create index(:sections, ["content_hash"], name: "unique_content_hash_index")
  end
end
