defmodule Hello.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :source, :text, null: false, default: "user"
    end

    alter table(:messages) do
      remove :sender_type
      modify :sender_id, :uuid, null: false
    end
  end

  def down do
    alter table(:messages) do
      modify :sender_id, :uuid, null: true
      add :sender_type, :text, null: false
    end

    alter table(:users) do
      remove :source
    end
  end
end
