defmodule Hello.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      remove :sender
    end

    alter table(:conversations) do
      add :user_id,
          references(:users,
            column: :id,
            name: "conversations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:conversations, "conversations_user_id_fkey")

    alter table(:conversations) do
      remove :user_id
    end

    alter table(:messages) do
      add :sender, :text, null: false
    end
  end
end
