defmodule Hello.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sections) do
      add :content_hash, :text, null: false
    end

    create index(:sections, ["content_hash"], name: "unique_content_hash_index")
  end

  def down do
    drop_if_exists index(:sections, ["content_hash"], name: "unique_content_hash_index")

    alter table(:sections) do
      remove :content_hash
    end
  end
end
